name: Updates

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: npm install

      - run: npm install -g npm-check-updates

      - name: Check for Updates
        run: ncu -u
    
      - name: Install Updates
        run: npm install
      
      - run: npm test
        env: 
          APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
        
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'main'
      
#       - name: Create Pull Request with Updates
#         uses: peter-evans/create-pull-request@v3
#         with:
#           delete-branch: true
#           token: ${{ secrets.APPLITOOLSUPDATEBOT_TOKEN }}
#          push-to-fork: applitoolsupdatebot/tutorial-images-javascript
